spring.application.name=mitsu
spring.datasource.url=jdbc:mysql://localhost:3306/mitsudb
spring.datasource.username=root
spring.datasource.password=Anna@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true